# Generated by Django 5.2.7 on 2025-11-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('TI', 'TI'), ('Humanas', 'Humanas'), ('Ficção/Romance', 'Ficção Científica / Romance'), ('Saúde', 'Saúde'), ('Biológicas', 'Biológicas'), ('Exatas', 'Exatas')], max_length=100)),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
