# Generated by Django 5.2.7 on 2025-11-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='categoria',
            field=models.CharField(choices=[('TI', 'TI'), ('Humanas', 'Humanas'), ('FiccaoRomance', 'Ficção Científica / Romance'), ('Saúde', 'Saúde'), ('Biológicas', 'Biológicas'), ('Exatas', 'Exatas')], max_length=100),
        ),
    ]
